### ISSUE TITLE
Can you add a manpage?

### ISSUE THREAD

**Issue by williamjmorenor** [okulbilisim/todo.py#6]
Hi

I am trying to package your script in Fedora repo, can you please add a man page to your scritp?

Fedora Packaging Guidelines request than any ejecutable under /usr/bin should have a man page

It could be good if you release a versión of your script so I can use the versión in the package name

Regards

**Comment by williamjmorenor** [comment]
Hi

todocli is now part of the Fedora Repo :)

https://admin.fedoraproject.org/pkgdb/package/todocli/

It is finding his way in the Fedora Updates system, could be good to get some karma in the update:

https://admin.fedoraproject.org/updates/todocli-0.1-20140709gitf50c240.fc21?_csrf_token=9d72e3d60c54c277eedbf421b05037ac6e769782

So I will close this issue

**Comment by hmert** [comment]
Thank you @williamjmorenor :) so honored. We will add this to our README :clap:
